# Install OpenStack Neutron (Network) Service on OpenStack Controller
---
- name: "Install Neutron (Network) Service on OpenStack Controller"
  hosts: all
  user: root
  vars:
    neutron_db_username: 'neutron'
    neutron_db_password: 'n3utron'
    neutron_db_name: 'neutron'
    neutron_admin_pass: 'neutr0n'
    nova_db_username: 'nova'
    nova_admin_pass: 'nov4'
    rabbitmq_host: '127.0.0.1'
    rabbitmq_user: 'openstack'
    rabbitmq_password: 'openst4ck'
    my_management_ip: '0.0.0.0'
    internal_interface: enp0s8
    external_interface: enp0s3

  tasks:
  - name: "Install Nova Compute Service: Self Service Networks"
    yum: name={{ item }} state=latest
    with_items:
    - openstack-neutron 
    - openstack-neutron-ml2
    - openstack-neutron-linuxbridge
    - ebtables

  - name: "Configure Neutron DB Access"
    ini_file:
      backup: yes
      path: /etc/neutron/neutron.conf
      section: database
      option: connection
      value: mysql+pymysql://{{ neutron_db_username }}:{{ neutron_db_password }}@127.0.0.1/{{ neutron_db_name }}

  - name: "Configure Neutron RabbitMQ Access"
    ini_file:
      path: /etc/neutron/neutron.conf
      section: DEFAULT
      option: "{{ item.key }}"
      value: "{{ item.value }}"
    with_items:
      - { key: 'core_plugin', value: 'ml2' }
      - { key: 'service_plugins', value: 'router' }
      - { key: 'allow_overlapping_ips', value: True }
      - { key: 'notify_nova_on_port_status_changes',  value: True }
      - { key: 'notify_nova_on_port_data_changes',  value: True }
      - { key: 'transport_url', value: 'rabbit://{{ rabbitmq_user }}:{{ rabbitmq_password }}@{{ rabbitmq_host }}' }
      - { key: 'auth_strategy', value: 'keystone' }

  - name: "Configure Neutron Keystone Auth Access"
    ini_file:
      path: /etc/neutron/neutron.conf
      section: keystone_authtoken
      option: "{{ item.key }}"
      value: "{{ item.value }}"
    with_items:
      - { key: 'auth_uri', value: 'http://127.0.0.1:5000' }
      - { key: 'auth_url', value: 'http://127.0.0.1:35357' }
      - { key: 'memcached_servers', value: '127.0.0.1:11211' }
      - { key: 'auth_type',  value: 'password' }
      - { key: 'project_domain_name', value: 'Default' }
      - { key: 'user_domain_name', value: 'Default' }
      - { key: 'project_name', value: 'service' }
      - { key: 'username', value: '{{ neutron_db_username }}' }
      - { key: 'password', value: '{{ neutron_admin_pass }}' }

  - name: "Configure Neutron Nova Access"
    ini_file:
      path: /etc/neutron/neutron.conf
      section: nova
      option: "{{ item.key }}"
      value: "{{ item.value }}"
    with_items:
      - { key: 'auth_url', value: 'http://127.0.0.1:35357' }
      - { key: 'auth_type',  value: 'password' }
      - { key: 'project_domain_name', value: 'Default' }
      - { key: 'user_domain_name', value: 'Default' }
      - { key: 'project_name', value: 'service' }
      - { key: 'username', value: '{{ nova_db_username }}' }
      - { key: 'password', value: '{{ nova_admin_pass }}' }

  - name: "Configure Neutron Oslo Concurrency"
    ini_file:
      path: /etc/neutron/neutron.conf
      section: oslo_concurrency
      option: lock_path
      value: "/var/lib/neutron/tmp"

  - name: "Configure Neutron Modular Layer 2 ML2 Plugin"
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ml2
      option: "{{ item.key }}"
      value: "{{ item.value }}"
    with_items:
      - { key: 'type_drivers', value: 'flat,vlan' }
      - { key: 'tenant_network_types',  value: '' }
      - { key: 'mechanism_drivers', value: 'linuxbridge' }
      - { key: 'extension_drivers', value: 'port_security' }

  - name: "Configure provider virtual network as flat network"
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ml2_type_flat
      option: flat_networks
      value: "provider,external"

  - name: "Configure ipset security group"
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: securitygroup
      option: enable_ipset
      value: True

  - name: "Configure the Linux bridge agent"
    ini_file:
      path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      section: linux_bridge
      option: physical_interface_mappings
      value: "provider:{{ internal_interface }},external:{{ external_interface }}"

  - name: "Configure provider virtual network as flat network"
    ini_file:
      path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      section: vxlan
      option: enable_vxlan
      value: "false" 

  - name: "Configure security groups and configure the Linux bridge iptables firewall driver"
    ini_file:
      path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      section: linux_bridge
      option: "{{ item.key }}"
      value: "{{ item.value }}"
    with_items:
      - { key: 'enable_security_group', value: True }
      - { key: 'firewall_driver',  value: 'neutron.agent.linux.iptables_firewall.IptablesFirewallDriver' }

  - name: "Configure provider virtual network as flat network"
    ini_file:
      path: /etc/neutron/l3_agent.ini
      section: DEFAULT
      option: interface_driver
      value: "neutron.agent.linux.interface.BridgeInterfaceDriver"

  - name: "Configure the Neutron DHCP Agent"
    ini_file:
      path: /etc/neutron/dhcp_agent.ini
      section: DEFAULT
      option: "{{ item.key }}"
      value: "{{ item.value }}"
    with_items:
      - { key: 'interface_driver', value: 'neutron.agent.linux.interface.BridgeInterfaceDriver' }
      - { key: 'dhcp_driver', value: 'neutron.agent.linux.dhcp.Dnsmasq' }
      - { key: 'enable_isolated_metadata', value: 'True' }
