# Install Docker from CentOS 7 repo
---
- name: "Install docker"
  hosts: all
  user: root

  tasks:
  - name: "copy docker repository"
    copy: src=../files/docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root

  #- name: "update kernel to latest version"
  #  yum: name=kernel state=latest

  - name: "install docker"
    yum: name={{ item }} state=latest
    with_items:
    - docker-engine

  - name: "start and enable docker service"
    service: name=docker state=restarted enabled=yes
