# Install epel repository
---
- name: "Install epel repository"
  hosts: all
  user: root

  tasks:
  - name: "install epel release"
    yum: name={{ item }} state=latest
    with_items:
    - epel-release
